/**
 * Official listed companies on the Casablanca Stock Exchange (Bourse de Casablanca / CSE).
 * Provides canonical ticker symbols, company names, sectors, exchange name, and currency.
 */

export interface CseCompany {
  ticker: string; // e.g. "ATW"
  name: string; // e.g. "Attijariwafa Bank"
  exchange: string; // "Casablanca Stock Exchange"
  currency: string; // "MAD"
  sector: string; // e.g. "Banking", "Telecommunications"
  isin?: string; // International Securities Identification Number
  omkarSymbol?: string; // Symbol format for external providers (e.g. "ATW:CASABLANCA" or "ATW")
}

export const CSE_COMPANIES: CseCompany[] = [
  {
    ticker: "ATW",
    name: "Attijariwafa Bank",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Banking",
    isin: "MA0000011512",
    omkarSymbol: "ATW:CASABLANCA",
  },
  {
    ticker: "BCP",
    name: "Banque Centrale Populaire",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Banking",
    isin: "MA0000011884",
    omkarSymbol: "BCP:CASABLANCA",
  },
  {
    ticker: "BOA",
    name: "Bank of Africa",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Banking",
    isin: "MA0000010951",
    omkarSymbol: "BOA:CASABLANCA",
  },
  {
    ticker: "IAM",
    name: "Maroc Telecom",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Telecommunications",
    isin: "MA0000011488",
    omkarSymbol: "IAM:CASABLANCA",
  },
  {
    ticker: "LHM",
    name: "LafargeHolcim Maroc",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Building Materials",
    isin: "MA0000012320",
    omkarSymbol: "LHM:CASABLANCA",
  },
  {
    ticker: "TQA",
    name: "Taqa Morocco",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Utilities & Energy",
    isin: "MA0000012205",
    omkarSymbol: "TQA:CASABLANCA",
  },
  {
    ticker: "MSA",
    name: "Marsa Maroc",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Port Logistics & Transport",
    isin: "MA0000012296",
    omkarSymbol: "MSA:CASABLANCA",
  },
  {
    ticker: "AKT",
    name: "Akdital",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Healthcare",
    isin: "MA0000012569",
    omkarSymbol: "AKT:CASABLANCA",
  },
  {
    ticker: "CIH",
    name: "CIH Bank",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Banking",
    isin: "MA0000011454",
    omkarSymbol: "CIH:CASABLANCA",
  },
  {
    ticker: "CDM",
    name: "Crédit du Maroc",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Banking",
    isin: "MA0000010969",
    omkarSymbol: "CDM:CASABLANCA",
  },
  {
    ticker: "CFG",
    name: "CFG Bank",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Banking",
    isin: "MA0000012585",
    omkarSymbol: "CFG:CASABLANCA",
  },
  {
    ticker: "TGCC",
    name: "TGCC",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Construction & Engineering",
    isin: "MA0000012544",
    omkarSymbol: "TGCC:CASABLANCA",
  },
  {
    ticker: "ADH",
    name: "Douja Promotion Groupe Addoha",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Real Estate Development",
    isin: "MA0000011504",
    omkarSymbol: "ADH:CASABLANCA",
  },
  {
    ticker: "RDS",
    name: "Résidences Dar Saada",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Real Estate Development",
    isin: "MA0000012239",
    omkarSymbol: "RDS:CASABLANCA",
  },
  {
    ticker: "ALM",
    name: "Alliances Développement Immobilier",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Real Estate Development",
    isin: "MA0000011702",
    omkarSymbol: "ALM:CASABLANCA",
  },
  {
    ticker: "ARL",
    name: "Aradei Capital",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Real Estate Investment",
    isin: "MA0000012486",
    omkarSymbol: "ARL:CASABLANCA",
  },
  {
    ticker: "IMR",
    name: "Immorente Invest",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Real Estate Investment",
    isin: "MA0000012353",
    omkarSymbol: "IMR:CASABLANCA",
  },
  {
    ticker: "COS",
    name: "Cosumar",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Agri-Food & Sugar",
    isin: "MA0000012247",
    omkarSymbol: "COS:CASABLANCA",
  },
  {
    ticker: "LES",
    name: "Lesieur Cristal",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Agri-Food & Oils",
    isin: "MA0000012015",
    omkarSymbol: "LES:CASABLANCA",
  },
  {
    ticker: "MUT",
    name: "Mutandis SCA",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Consumer Goods",
    isin: "MA0000012387",
    omkarSymbol: "MUT:CASABLANCA",
  },
  {
    ticker: "MNG",
    name: "Managem",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Mining",
    isin: "MA0000011058",
    omkarSymbol: "MNG:CASABLANCA",
  },
  {
    ticker: "SMI",
    name: "Société Métallurgique d'Imiter",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Mining",
    isin: "MA0000011041",
    omkarSymbol: "SMI:CASABLANCA",
  },
  {
    ticker: "CMT",
    name: "Compagnie Minière de Touissit",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Mining",
    isin: "MA0000011793",
    omkarSymbol: "CMT:CASABLANCA",
  },
  {
    ticker: "HPS",
    name: "Hightech Payment Systems",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Fintech & IT",
    isin: "MA0000011579",
    omkarSymbol: "HPS:CASABLANCA",
  },
  {
    ticker: "DIS",
    name: "Disway",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "IT Distribution",
    isin: "MA0000011603",
    omkarSymbol: "DIS:CASABLANCA",
  },
  {
    ticker: "MIC",
    name: "Microdata",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "IT Services",
    isin: "MA0000012148",
    omkarSymbol: "MIC:CASABLANCA",
  },
  {
    ticker: "DWY",
    name: "Disty Technologies",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "IT Hardware",
    isin: "MA0000012551",
    omkarSymbol: "DWY:CASABLANCA",
  },
  {
    ticker: "SOT",
    name: "Sothema",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Pharmaceuticals",
    isin: "MA0000011462",
    omkarSymbol: "SOT:CASABLANCA",
  },
  {
    ticker: "LAP",
    name: "Label Vie",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Retail & Supermarkets",
    isin: "MA0000011751",
    omkarSymbol: "LAP:CASABLANCA",
  },
  {
    ticker: "WAA",
    name: "Wafa Assurance",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Insurance",
    isin: "MA0000010928",
    omkarSymbol: "WAA:CASABLANCA",
  },
  {
    ticker: "SML",
    name: "Sanlam Maroc",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Insurance",
    isin: "MA0000010936",
    omkarSymbol: "SML:CASABLANCA",
  },
  {
    ticker: "ATL",
    name: "AtlantaSanad",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Insurance",
    isin: "MA0000011686",
    omkarSymbol: "ATL:CASABLANCA",
  },
  {
    ticker: "CMA",
    name: "Ciments du Maroc",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Building Materials",
    isin: "MA0000010993",
    omkarSymbol: "CMA:CASABLANCA",
  },
  {
    ticker: "COL",
    name: "Colorado",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Building Materials & Paints",
    isin: "MA0000011538",
    omkarSymbol: "COL:CASABLANCA",
  },
  {
    ticker: "SID",
    name: "Sonasid",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Steel & Metallurgy",
    isin: "MA0000010019",
    omkarSymbol: "SID:CASABLANCA",
  },
  {
    ticker: "AFM",
    name: "Afriquia Gaz",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Oil & Gas Distribution",
    isin: "MA0000010944",
    omkarSymbol: "AFM:CASABLANCA",
  },
  {
    ticker: "TMR",
    name: "TotalEnergies Marketing Maroc",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Oil & Gas Distribution",
    isin: "MA0000012270",
    omkarSymbol: "TMR:CASABLANCA",
  },
  {
    ticker: "SNP",
    name: "SNEP",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Chemicals",
    isin: "MA0000011652",
    omkarSymbol: "SNP:CASABLANCA",
  },
  {
    ticker: "ATH",
    name: "Auto Hall",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Automotive Distribution",
    isin: "MA0000010266",
    omkarSymbol: "ATH:CASABLANCA",
  },
  {
    ticker: "ENK",
    name: "Ennakl Automobiles",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Automotive Distribution",
    isin: "TN0007420015",
    omkarSymbol: "ENK:CASABLANCA",
  },
  {
    ticker: "SBM",
    name: "Société des Boissons du Maroc",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Beverages",
    isin: "MA0000010068",
    omkarSymbol: "SBM:CASABLANCA",
  },
  {
    ticker: "DHO",
    name: "Delta Holding",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Diversified Holding",
    isin: "MA0000011785",
    omkarSymbol: "DHO:CASABLANCA",
  },
  {
    ticker: "JET",
    name: "Jet Contractors",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Construction & Engineering",
    isin: "MA0000012163",
    omkarSymbol: "JET:CASABLANCA",
  },
  {
    ticker: "EQD",
    name: "Eqdom",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Financing & Credit",
    isin: "MA0000010043",
    omkarSymbol: "EQD:CASABLANCA",
  },
  {
    ticker: "SLF",
    name: "Salafin",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Financing & Credit",
    isin: "MA0000011694",
    omkarSymbol: "SLF:CASABLANCA",
  },
  {
    ticker: "RIS",
    name: "Risma",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Hotels & Tourism",
    isin: "MA0000011520",
    omkarSymbol: "RIS:CASABLANCA",
  },
  {
    ticker: "MAG",
    name: "Maghreb Oxygène",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Chemicals & Gases",
    isin: "MA0000010308",
    omkarSymbol: "MAG:CASABLANCA",
  },
  {
    ticker: "DIM",
    name: "Dari Couspate",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Agri-Food",
    isin: "MA0000011264",
    omkarSymbol: "DIM:CASABLANCA",
  },
  {
    ticker: "CRS",
    name: "Cartier Saada",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Agri-Food",
    isin: "MA0000011561",
    omkarSymbol: "CRS:CASABLANCA",
  },
  {
    ticker: "UNM",
    name: "Unimer",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Agri-Food & Seafood",
    isin: "MA0000011322",
    omkarSymbol: "UNM:CASABLANCA",
  },
];

/**
 * Searches companies listed on the Casablanca Stock Exchange.
 * Matches case-insensitively on ticker, company name, or sector.
 */
export function searchCseCompanies(query: string): CseCompany[] {
  const trimmed = query.trim().toLowerCase();
  if (!trimmed) {
    return CSE_COMPANIES;
  }

  return CSE_COMPANIES.filter((company) => {
    const matchTicker = company.ticker.toLowerCase().includes(trimmed);
    const matchName = company.name.toLowerCase().includes(trimmed);
    const matchSector = company.sector.toLowerCase().includes(trimmed);
    return matchTicker || matchName || matchSector;
  });
}

/**
 * Retrieves a Casablanca Stock Exchange company by ticker symbol.
 */
export function getCseCompany(ticker: string): CseCompany | null {
  if (!ticker) return null;
  const cleanTicker = ticker.trim().toUpperCase();
  return CSE_COMPANIES.find((c) => c.ticker === cleanTicker) || null;
}
