/**
 * Official listed companies on the Casablanca Stock Exchange (Bourse de Casablanca / CSE).
 * Provides canonical ticker symbols, company names, sectors, exchange name, and currency.
 */

export interface CseCompany {
  ticker: string; // e.g. "ATW"
  name: string; // e.g. "Attijariwafa Bank"
  exchange: string; // "Casablanca Stock Exchange"
  currency: string; // "MAD"
  sector: string; // e.g. "Banking", "Telecommunications"
  isin?: string; // International Securities Identification Number
  ficheUrl?: string; // Bourse de Casablanca fiche URL
}

export const CSE_COMPANIES: CseCompany[] = [
  {
    ticker: "ATW",
    name: "Attijariwafa Bank",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Banking",
    isin: "MA0000012445",
    ficheUrl: "https://www.casablanca-bourse.com/live-market/actions/fiche/ATW",
  },
  {
    ticker: "BCP",
    name: "Banque Centrale Populaire",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Banking",
    isin: "MA0000011884",
    ficheUrl: "https://www.casablanca-bourse.com/live-market/actions/fiche/BCP",
  },
  {
    ticker: "BOA",
    name: "Bank of Africa",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Banking",
    isin: "MA0000010951",
    ficheUrl: "https://www.casablanca-bourse.com/live-market/actions/fiche/BOA",
  },
  {
    ticker: "IAM",
    name: "Maroc Telecom",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Telecommunications",
    isin: "MA0000011488",
    ficheUrl: "https://www.casablanca-bourse.com/live-market/actions/fiche/IAM",
  },
  {
    ticker: "LHM",
    name: "LafargeHolcim Maroc",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Building Materials",
    isin: "MA0000012320",
    ficheUrl: "https://www.casablanca-bourse.com/live-market/actions/fiche/LHM",
  },
  {
    ticker: "TQA",
    name: "Taqa Morocco",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Utilities & Energy",
    isin: "MA0000012205",
    ficheUrl: "https://www.casablanca-bourse.com/live-market/actions/fiche/TQA",
  },
  {
    ticker: "MSA",
    name: "Marsa Maroc",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Port Logistics & Transport",
    isin: "MA0000012296",
    ficheUrl: "https://www.casablanca-bourse.com/live-market/actions/fiche/MSA",
  },
  {
    ticker: "AKT",
    name: "Akdital",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Healthcare",
    isin: "MA0000012569",
    ficheUrl: "https://www.casablanca-bourse.com/live-market/actions/fiche/AKT",
  },
  {
    ticker: "CIH",
    name: "CIH Bank",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Banking",
    isin: "MA0000011454",
    ficheUrl: "https://www.casablanca-bourse.com/live-market/actions/fiche/CIH",
  },
  {
    ticker: "CDM",
    name: "Crédit du Maroc",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Banking",
    isin: "MA0000010969",
    ficheUrl: "https://www.casablanca-bourse.com/live-market/actions/fiche/CDM",
  },
  {
    ticker: "CFG",
    name: "CFG Bank",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Banking",
    isin: "MA0000012585",
    ficheUrl: "https://www.casablanca-bourse.com/live-market/actions/fiche/CFG",
  },
  {
    ticker: "TGCC",
    name: "TGCC",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Construction & Engineering",
    isin: "MA0000012544",
    ficheUrl: "https://www.casablanca-bourse.com/live-market/actions/fiche/TGCC",
  },
  {
    ticker: "ADH",
    name: "Douja Promotion Groupe Addoha",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Real Estate Development",
    isin: "MA0000011504",
    ficheUrl: "https://www.casablanca-bourse.com/live-market/actions/fiche/ADH",
  },
  {
    ticker: "RDS",
    name: "Résidences Dar Saada",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Real Estate Development",
    isin: "MA0000012239",
    ficheUrl: "https://www.casablanca-bourse.com/live-market/actions/fiche/RDS",
  },
  {
    ticker: "ALM",
    name: "Alliances Développement Immobilier",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Real Estate Development",
    isin: "MA0000011702",
    ficheUrl: "https://www.casablanca-bourse.com/live-market/actions/fiche/ALM",
  },
  {
    ticker: "ARL",
    name: "Aradei Capital",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Real Estate Investment",
    isin: "MA0000012486",
    ficheUrl: "https://www.casablanca-bourse.com/live-market/actions/fiche/ARL",
  },
  {
    ticker: "IMR",
    name: "Immorente Invest",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Real Estate Investment",
    isin: "MA0000012353",
    ficheUrl: "https://www.casablanca-bourse.com/live-market/actions/fiche/IMR",
  },
  {
    ticker: "COS",
    name: "Cosumar",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Agri-Food & Sugar",
    isin: "MA0000012247",
    ficheUrl: "https://www.casablanca-bourse.com/live-market/actions/fiche/COS",
  },
  {
    ticker: "LES",
    name: "Lesieur Cristal",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Agri-Food & Oils",
    isin: "MA0000012015",
    ficheUrl: "https://www.casablanca-bourse.com/live-market/actions/fiche/LES",
  },
  {
    ticker: "MUT",
    name: "Mutandis SCA",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Consumer Goods",
    isin: "MA0000012387",
    ficheUrl: "https://www.casablanca-bourse.com/live-market/actions/fiche/MUT",
  },
  {
    ticker: "MNG",
    name: "Managem",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Mining",
    isin: "MA0000011058",
    ficheUrl: "https://www.casablanca-bourse.com/live-market/actions/fiche/MNG",
  },
  {
    ticker: "SMI",
    name: "Société Métallurgique d'Imiter",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Mining",
    isin: "MA0000011041",
    ficheUrl: "https://www.casablanca-bourse.com/live-market/actions/fiche/SMI",
  },
  {
    ticker: "CMT",
    name: "Compagnie Minière de Touissit",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Mining",
    isin: "MA0000011793",
    ficheUrl: "https://www.casablanca-bourse.com/live-market/actions/fiche/CMT",
  },
  {
    ticker: "HPS",
    name: "Hightech Payment Systems",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Fintech & IT",
    isin: "MA0000011579",
    ficheUrl: "https://www.casablanca-bourse.com/live-market/actions/fiche/HPS",
  },
  {
    ticker: "DIS",
    name: "Disway",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "IT Distribution",
    isin: "MA0000011603",
    ficheUrl: "https://www.casablanca-bourse.com/live-market/actions/fiche/DIS",
  },
  {
    ticker: "MIC",
    name: "Microdata",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "IT Services",
    isin: "MA0000012148",
    ficheUrl: "https://www.casablanca-bourse.com/live-market/actions/fiche/MIC",
  },
  {
    ticker: "DWY",
    name: "Disty Technologies",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "IT Hardware",
    isin: "MA0000012551",
    ficheUrl: "https://www.casablanca-bourse.com/live-market/actions/fiche/DWY",
  },
  {
    ticker: "SOT",
    name: "Sothema",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Pharmaceuticals",
    isin: "MA0000011462",
    ficheUrl: "https://www.casablanca-bourse.com/live-market/actions/fiche/SOT",
  },
  {
    ticker: "LAP",
    name: "Label Vie",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Retail & Supermarkets",
    isin: "MA0000011751",
    ficheUrl: "https://www.casablanca-bourse.com/live-market/actions/fiche/LAP",
  },
  {
    ticker: "WAA",
    name: "Wafa Assurance",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Insurance",
    isin: "MA0000010928",
    ficheUrl: "https://www.casablanca-bourse.com/live-market/actions/fiche/WAA",
  },
  {
    ticker: "SML",
    name: "Sanlam Maroc",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Insurance",
    isin: "MA0000010936",
    ficheUrl: "https://www.casablanca-bourse.com/live-market/actions/fiche/SML",
  },
  {
    ticker: "ATL",
    name: "AtlantaSanad",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Insurance",
    isin: "MA0000011686",
    ficheUrl: "https://www.casablanca-bourse.com/live-market/actions/fiche/ATL",
  },
  {
    ticker: "CMA",
    name: "Ciments du Maroc",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Building Materials",
    isin: "MA0000010993",
    ficheUrl: "https://www.casablanca-bourse.com/live-market/actions/fiche/CMA",
  },
  {
    ticker: "COL",
    name: "Colorado",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Building Materials & Paints",
    isin: "MA0000011538",
    ficheUrl: "https://www.casablanca-bourse.com/live-market/actions/fiche/COL",
  },
  {
    ticker: "SID",
    name: "Sonasid",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Steel & Metallurgy",
    isin: "MA0000010019",
    ficheUrl: "https://www.casablanca-bourse.com/live-market/actions/fiche/SID",
  },
  {
    ticker: "AFM",
    name: "Afriquia Gaz",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Oil & Gas Distribution",
    isin: "MA0000010944",
    ficheUrl: "https://www.casablanca-bourse.com/live-market/actions/fiche/AFM",
  },
  {
    ticker: "TMR",
    name: "TotalEnergies Marketing Maroc",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Oil & Gas Distribution",
    isin: "MA0000012270",
    ficheUrl: "https://www.casablanca-bourse.com/live-market/actions/fiche/TMR",
  },
  {
    ticker: "SNP",
    name: "SNEP",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Chemicals",
    isin: "MA0000011652",
    ficheUrl: "https://www.casablanca-bourse.com/live-market/actions/fiche/SNP",
  },
  {
    ticker: "ATH",
    name: "Auto Hall",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Automotive Distribution",
    isin: "MA0000010266",
    ficheUrl: "https://www.casablanca-bourse.com/live-market/actions/fiche/ATH",
  },
  {
    ticker: "ENK",
    name: "Ennakl Automobiles",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Automotive Distribution",
    isin: "TN0007420015",
    ficheUrl: "https://www.casablanca-bourse.com/live-market/actions/fiche/ENK",
  },
  {
    ticker: "SBM",
    name: "Société des Boissons du Maroc",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Beverages",
    isin: "MA0000010068",
    ficheUrl: "https://www.casablanca-bourse.com/live-market/actions/fiche/SBM",
  },
  {
    ticker: "DHO",
    name: "Delta Holding",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Diversified Holding",
    isin: "MA0000011785",
    ficheUrl: "https://www.casablanca-bourse.com/live-market/actions/fiche/DHO",
  },
  {
    ticker: "JET",
    name: "Jet Contractors",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Construction & Engineering",
    isin: "MA0000012163",
    ficheUrl: "https://www.casablanca-bourse.com/live-market/actions/fiche/JET",
  },
  {
    ticker: "EQD",
    name: "Eqdom",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Financing & Credit",
    isin: "MA0000010043",
    ficheUrl: "https://www.casablanca-bourse.com/live-market/actions/fiche/EQD",
  },
  {
    ticker: "SLF",
    name: "Salafin",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Financing & Credit",
    isin: "MA0000011694",
    ficheUrl: "https://www.casablanca-bourse.com/live-market/actions/fiche/SLF",
  },
  {
    ticker: "RIS",
    name: "Risma",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Hotels & Tourism",
    isin: "MA0000011520",
    ficheUrl: "https://www.casablanca-bourse.com/live-market/actions/fiche/RIS",
  },
  {
    ticker: "MAG",
    name: "Maghreb Oxygène",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Chemicals & Gases",
    isin: "MA0000010308",
    ficheUrl: "https://www.casablanca-bourse.com/live-market/actions/fiche/MAG",
  },
  {
    ticker: "DIM",
    name: "Dari Couspate",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Agri-Food",
    isin: "MA0000011264",
    ficheUrl: "https://www.casablanca-bourse.com/live-market/actions/fiche/DIM",
  },
  {
    ticker: "CRS",
    name: "Cartier Saada",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Agri-Food",
    isin: "MA0000011561",
    ficheUrl: "https://www.casablanca-bourse.com/live-market/actions/fiche/CRS",
  },
  {
    ticker: "UNM",
    name: "Unimer",
    exchange: "Casablanca Stock Exchange",
    currency: "MAD",
    sector: "Agri-Food & Seafood",
    isin: "MA0000011322",
    ficheUrl: "https://www.casablanca-bourse.com/live-market/actions/fiche/UNM",
  },
];

/**
 * Searches companies listed on the Casablanca Stock Exchange.
 * Matches case-insensitively on ticker, company name, or sector.
 */
export function searchCseCompanies(query: string): CseCompany[] {
  const trimmed = query.trim().toLowerCase();
  if (!trimmed) {
    return CSE_COMPANIES;
  }

  return CSE_COMPANIES.filter((company) => {
    const matchTicker = company.ticker.toLowerCase().includes(trimmed);
    const matchName = company.name.toLowerCase().includes(trimmed);
    const matchSector = company.sector.toLowerCase().includes(trimmed);
    return matchTicker || matchName || matchSector;
  });
}

/**
 * Retrieves a Casablanca Stock Exchange company by ticker symbol.
 */
export function getCseCompany(ticker: string): CseCompany | null {
  if (!ticker) return null;
  const cleanTicker = ticker.trim().toUpperCase();
  return CSE_COMPANIES.find((c) => c.ticker === cleanTicker) || null;
}
